//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountProfiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountProfiles()
        {
            this.isCompany = false;
            this.Rating = 0;
            this.Ranking = 0;
            this.Trips = 0;
            this.Distance = 0D;
            this.DriveTimeInMin = 0;
            this.HardBreaks = 0;
            this.HardAccelerations = 0;
            this.FuelConsumption = 0D;
            this.MaxSpeed = 0D;
            this.AverageSpeed = 0D;
            this.Deleted = false;
            this.OverSpeeds = 0;
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LoginID { get; set; }
        public string LoginPassword { get; set; }
        public string ProfilePictureUri { get; set; }
        public Nullable<bool> isCompany { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Ranking { get; set; }
        public Nullable<int> Trips { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<int> DriveTimeInMin { get; set; }
        public Nullable<int> HardBreaks { get; set; }
        public Nullable<int> HardAccelerations { get; set; }
        public Nullable<double> FuelConsumption { get; set; }
        public Nullable<double> MaxSpeed { get; set; }
        public Nullable<double> AverageSpeed { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> MidnightDriveInMin { get; set; }
        public Nullable<int> OverSpeeds { get; set; }
        public Nullable<int> TimeZone { get; set; }
    }
}
