//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardMonthlyData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DashboardMonthlyData()
        {
            this.DurationInMin = 0;
            this.Mileage = 0D;
            this.Score = 0;
            this.NegativeEvents = 0;
            this.Trips = 0;
            this.Deleted = false;
        }
    
        public int Id { get; set; }
        public int AccountID { get; set; }
        public string YearMonth { get; set; }
        public Nullable<int> DurationInMin { get; set; }
        public Nullable<double> Mileage { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> NegativeEvents { get; set; }
        public Nullable<int> Trips { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
