//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devices()
        {
            this.isActive = false;
            this.AccelerationAxis = "\'X\'";
            this.HardAccelerationValue = 2D;
            this.HardBreakValue = -2D;
            this.Deleted = false;
        }
    
        public string IoTHubDeviceID { get; set; }
        public string IoTHubHostName { get; set; }
        public string IoTHubProtocol { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string AccelerationAxis { get; set; }
        public Nullable<double> HardAccelerationValue { get; set; }
        public Nullable<double> HardBreakValue { get; set; }
        public string RegisterCountry { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
