//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trips
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trips()
        {
            this.Distance = 0D;
            this.HardBreaks = 0;
            this.HardAccelerations = 0;
            this.OverSpeeds = 0;
            this.MaxSpeed = 0D;
            this.AverageSpeed = 0D;
            this.MidNightDriveInSec = 0;
            this.DriveTimeInSec = 0;
            this.IdelingTimeInSec = 0;
            this.ProcessCompleteFlag = false;
            this.Rating = 0;
            this.CenterLat = 0m;
            this.CenterLng = 0m;
            this.MaxLat = 0m;
            this.Maxlng = 0m;
            this.MinLat = 0m;
            this.MinLng = 0m;
            this.Deleted = false;
        }
    
        public string Id { get; set; }
        public string CarID { get; set; }
        public string IoTHubDeviceID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public long StartTimeStamp { get; set; }
        public Nullable<long> EndTimeStamp { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public string StartCountry { get; set; }
        public string EndCountry { get; set; }
        public Nullable<bool> isComplete { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<int> HardBreaks { get; set; }
        public Nullable<int> HardAccelerations { get; set; }
        public Nullable<int> OverSpeeds { get; set; }
        public Nullable<double> MaxSpeed { get; set; }
        public Nullable<double> AverageSpeed { get; set; }
        public Nullable<int> MidNightDriveInSec { get; set; }
        public Nullable<int> DriveTimeInSec { get; set; }
        public Nullable<int> IdelingTimeInSec { get; set; }
        public Nullable<bool> ProcessCompleteFlag { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<decimal> CenterLat { get; set; }
        public Nullable<decimal> CenterLng { get; set; }
        public Nullable<decimal> MaxLat { get; set; }
        public Nullable<decimal> Maxlng { get; set; }
        public Nullable<decimal> MinLat { get; set; }
        public Nullable<decimal> MinLng { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
